data:
  output_topic: /lidar_perception_tracker/streams/pointcloud
  publish_rate: 10.0
  sequence: '0000'
  source: ~/kitti_dataset/
detection:
  euclidean:
    eps: 1.259
    max_center_z: 1.651
    max_h: 2.5
    max_l: 5.5
    max_w: 2.5
    min_h: 0.5
    min_l: 0.5
    min_points: 12
    min_w: 0.3
  mode: pvrcnn
  output_topic: /lidar_perception_tracker/streams/detections
  point_pillars:
    conf_threshold: 0.6
    device: cuda
    model_path: models/pointpillar_7728.pth
    nms_threshold: 0.5
  fusion:
    nms_distance: 1.5
  pvrcnn:
    cfg_file: models/pvrcnn.yaml
    conf_threshold: 0.8
    device: cuda
    model_path: models/pvrcnn.pth
  second:
    cfg_file: models/second.yaml
    conf_threshold: 0.5
    device: cuda
    model_path: models/second.pth
  voxel_rcnn:
    cfg_file: models/voxel_rcnn_car.yaml
    conf_threshold: 0.5
    device: cuda
    model_path: models/voxel_rcnn_car.pth
evaluation:
  match_distance: 2.0
preprocessing:
  ground_threshold: 0.2
  max_distance: 50.0
  min_distance: 2.0
  output_topic: /lidar_perception_tracker/streams/pointcloud_preprocessed
  voxel_size: 0.2
tracking:
  euclidean:
    match_distance: 2.0
    max_age: 5
    min_hits: 3
  fusion:
    match_distance: 2.583
    max_age: 6
    min_hits: 5
  kalman_initial_measurement_covariance: 1.0
  kalman_initial_state_covariance: 1.0
  kalman_measurement_noise: 1e-2
  kalman_process_noise: 1e-5
  output_topic: /lidar_perception_tracker/streams/tracks
  point_pillars:
    match_distance: 3.85
    max_age: 3
    min_hits: 2
  pvrcnn:
    match_distance: 2.583
    max_age: 6
    min_hits: 5
  second:
    match_distance: 3.0
    max_age: 3
    min_hits: 2
  use_kalman_filter: true
  voxel_rcnn:
    match_distance: 3.0
    max_age: 3
    min_hits: 2
